- name: Set up ERPNext
  hosts: all
  vars:
    domain: dewi.communtu.org
    composeProject: erpnext
    composeFolder: "{{ ansible_user_dir }}/.cache/{{ composeProject }}"
    repo: "https://github.com/frappe/frappe_docker"
    # 2023-03-22 / ERPNext v14.19.0
    repo_version: 786c5d19d261ea9068c3069161f523ab577fcf1b
    erpnext_version: v14.19.0 
  roles:
    - erpnext
