# based on https://github.com/frappe/frappe_docker/blob/develop/installation/docker-compose-networks.yml
# changes:
# * separate (internal) default network and (external) proxy network
# * make name of proxy network configurable
version: '3'

networks:
  default:
  proxy:
    name: ${PROXY_NETWORK:-webproxy}

services:
  frontend:
    environment:
      - VIRTUAL_HOST=${SITES}
      - LETSENCRYPT_HOST=${SITES}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - default
      - proxy
      